# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7146adb87356cc4f3ccaabfc36b8ae4a5fc0f7ef95d779c942ad182f789a0efdd44a3848cafb6f2e018f3bfc1ab9af997bc766848d1fe4df0a5191a9e917b8b

test:
  secret_key_base: ec988f7f30f6d15b3ef70cd664eef2bf45bf21a7bb04b8c8f9686bb4ba4d10baa8277314e8fc78775a24a24731a6d9290d0ea9704dbecdd1e635fd2a31420e8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
